### ISSUE TITLE
Please add the images which you used in Notebook file

### ISSUE THREAD

**Issue by yunho0130** [SungchulLee/reinforcement_learning#1]
Please check below screenshot. 
![image](https://user-images.githubusercontent.com/7574765/54271630-3dd8c100-45c5-11e9-93d6-167a586257b0.png)

**Comment by SungchulLee** [comment]
Done

**Comment by SungchulLee** [comment]
done

2019년 3월 13일 (수) 오후 7:21, Yunho Maeng <notifications@github.com>님이 작성:
